
<h2 style="text-align:center;">Formulario</h2>	
<div id="form_agregar" class="well">
	    <a class="btn btn-success" href="/usuario/list"><i class="icon-list icon-white"></i> Listar</a>
	    <a class="btn" href="/usuario/add"><i class="icon-refresh"></i> Actualizar</a>
	    <br>
	    <br>
		<div class="alert alert-info" id="notices">
		            Llene el formulario teniendo en cuenta los requeridos que están con (*).
		</div>  	    
		<?php echo $this->form;?>
</div>
<script type="text/javascript">
	$(function(){
		$("#us_user").focusout(function(){
			$.post("/async/validuserbd",{us_user :$("#us_user").val() },function(response){
						if (response==1) {
							$('input[type="submit"]').attr('disabled','disabled');	
							$("#notices").removeClass();
							$("#notices").addClass("alert alert-error");	
							$("#notices").html("<h4 class='alert-heading'>Error</h4>El usuario. '"+$("#us_user").val()+"' ya se encuentra registrado.");
						}
						if(response == 0){	
							$('input[type="submit"]').removeAttr('disabled');
							$("#notices").removeClass();
							$("#notices").addClass("alert alert-success");						
							$("#notices").html("<h4 class='alert-heading'>Bién</h4>El Nombre. '"+$("#us_user").val()+" ' está disponible. ;-)");
						}
					});

			return false;
		});
		$("#frmUsuario").submit(function(){
			if($("#idprivilegio").val()==0 && $("#idpersonal").val()==0){
				alert('Debe de eligir privilegio y Personal');
				return false;
			}

			if(!$("#idprivilegio").val()==0 && $("#idpersonal").val()==0){
				alert('Elige Personal');
				return false;
			}

			if($("#idprivilegio").val()==0 && !$("#idpersonal").val()==0){
				alert('Elige privilegio');
				return false;
			}

		});
	});

</script>