<article>
    <h2>Sección de IGV</h2>
    <form class="well">
        <label style="float:right;">
            <a class="btn" href="/igv/list"><i class="icon-refresh"></i> Actualizar</a>&nbsp;
            <a class="btn btn-info" href="/igv/add" id="create-new" title="Agregar Nuevo"><i class="icon-plus icon-white"></i> Nuevo </a>
        </label>
    </form>
</article>
<article id="tblistar">
    <table class="table table-striped table-bordered table-condensed">
            <thead>
               <tr>
                    <th>Id</th>
                    <th>Tasa</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                </tr>
            </thead>        
            <?php if( count( $this->paginator )) :?>
            <?php $contador = 0; ?>
            <tbody>
                <?php foreach ($this->paginator as $value) : ?>
                <?php $contador++; ?>           
                <tr>
                    <td><?php echo $value->idigv;?></td>
                    <td><?php echo $value->ig_tasa;?></td>
                    <td><?php echo $value->ig_estado;?></td>
                    <td width="88">                      
                        <div class="btn-group">
                          <a class="btn btn-mini btn-primary" href="#">Acción</a>
                          <a class="btn btn-mini btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                          <ul class="dropdown-menu" style="text-align:left;">
                            <li><a href="/igv/update/id/<?php echo $value->idigv; ?>" onclick= "AlertUpdate(<?php echo $value->idigv; ?>)" rel="popover" data-content="Si modifica este IGV todos los registros vendidos con este valor se cambiarán automáticamente, y luego te traería reportes falsos a la hora de consultar." data-original-title="Atención"><i class="icon-pencil"></i> Editar</a></li>
                            <li>
                                <a href="/igv/delete/id/<?php echo $value->idigv; ?>" onclick= "AlertDelete(<?php echo $value->idigv; ?>)" rel="popover" data-content="Si elimina, se perderán todos los registros relacionados con este registro" data-original-title="Atención">
                                    <i class="icon-trash"></i> Eliminar
                                </a>
                            </li>
                          </ul>
                        </div>                      
                    </td>
                </tr>          
            <?php endforeach;?>
            </tbody>        
            <?php else : ?>
            <tbody>
                <tr>
                    <td colspan="5">No hay datos</td>
                </tr>
            </tbody>
            <?php endif;?> 
            <tfoot>
                <tr >
                    <td colspan="5" style="text-algn:right;padding-left:auto;">
                        <?php if( count( $this->paginator )):?>
                            <?php echo $this->paginator;?>
                        <?php endif;?>  
                    </td>
                </tr>      
            </tfoot>
    </table>
</article>
<script type="text/javascript">
    function AlertDelete (argument) {
        if(confirm("Desea eliminar el registro?")){
            window.location.replace('/igv/delete/id/'+argument);
        }else{
            return false;
        }
    }
    function AlertUpdate (argument) {
        if(confirm("Realmente quiere modificar el registro?")){
            window.location.replace('/igv/update/id/'+argument);
        }else{
            return false;
        }
    }
</script>
