<article>
    <h2>Relación de Facturas y/o Compras</h2>
    <form id="frmbuscar" class="well form-search">
        <input id="txtbuscar" type="text" class="input-large search-query" placeholder="Quieres Buscar?..">
        <button id="btnbuscar" type="submit" class="btn btn-inverse"><i class="icon-search icon-white"></i> Buscar</button>&nbsp;&nbsp;
        <span></span>
        <label style="float:right;">
            <a class="btn" href="/compra/list"><i class="icon-refresh"></i> Actualizar</a>&nbsp;
            <a class="btn btn-info" href="/compra/add" id="create-new" title="Agregar Nuevo"><i class="icon-plus icon-white"></i> Nueva Compra </a>
        </label>
    </form>
</article>
<article id="tblistar">
    <table class="table table-striped table-bordered table-condensed" style="font-size:11px">
            <thead>
               <tr>
                    <th>Id</th>
                    <th>Nro. Fact.</th>
                    <th>Fech. Compra</th>
                    <th>Importe</th>
                    <th>Encargado</th>
                    <th>Proveedor</th>
                    <th>Personal</th>
                    <th>Acciones</th>
                </tr>
            </thead>        
            <?php if( count( $this->paginator )) :?>
            <tbody>
                <?php foreach ($this->paginator as $value) : ?>      
                <tr>
                    <td><?php echo $value->idcompra;?></td>
                    <td><?php echo $value->co_nrofact;?></td>
                    <td><?php echo $value->co_fech;?></td>
                    <td><?php echo $value->co_importe;?></td>
                    <td><?php echo $value->co_encargado;?></td>
                    <td><?php echo $value->pro_nombre;?></td>
                    <td><?php echo $value->per_nombre;?></td>
                    <td width="77">                      
                        <div class="btn-group">
                          <a class="btn btn-mini btn-primary" href="#">Acción</a>
                          <a class="btn btn-mini btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                          <ul class="dropdown-menu" style="text-align:left;">
                            <li><a href="/compra/update/id/<?php echo $value->idcompra; ?>"><i class="icon-pencil"></i> Editar</a></li>
                            <li id="acciones"><a href="/compra/delete/id/<?php echo $value->idcompra; ?>"  rel="popover" data-content="Si elimina, se perderán todos los registros relacionados con este registro" data-original-title="Atención"><i class="icon-trash"></i> Eliminar</a></li>
                            <li id="detalles"><a href="/async/detailsshop/id/<?php echo $value->idcompra; ?>"><i class="icon-list"></i> Detallar</a></li>  
                            <li><a href="#" onClick="abrirVentana('http://punto4.local/async/printdetailsshop/id/<?php echo $value->idcompra; ?>')"><i class="icon-print"></i> Imprimir Detalle</a></li>  
                          </ul>
                        </div>                      
                    </td>
                </tr>          
            <?php endforeach;?>
            </tbody>        
            <?php else : ?>
            <tbody>
                <tr>
                    <td colspan="8">No hay datos</td>
                </tr>
            </tbody>
            <?php endif;?> 
            <tfoot>
                <tr >
                    <td colspan="8">
                        <?php if( count( $this->paginator )):?>
                            <?php echo $this->paginator;?>
                        <?php endif;?>  
                    </td>
                </tr>      
            </tfoot>
    </table>
</article>

<a href="#" class="tooltip-test" data-original-title="Tooltip gjjjdkdjkd s;dladjfhsf adhjhfdjkhjkhfs adklhadhfh">This link</a> and <a href="#" class="tooltip-test" data-original-title="Tooltip">that link</a>


<!-- La parte en donde se busca para listar la lista en la parte de abajo -->
<script type="text/javascript">
    $(function(){
    // Script para buscar las compras
        $("#frmbuscar").submit(function(){
            $.post("/compra/searchcompra",{txtbuscar : $("#txtbuscar").val()},function(response){
                    var notice = response;
                     $("#tblistar").html(notice);
                });
            return false;
        });

    // Evento para poder pedir confirmación al moneto de eliminar un registro
        $("#acciones a").click(function(e){            
            if (confirm('Realmente quiere eliminarlo el registro?')){
                return true;
            }
            else{
                e.preventDefault();
            }
        });    


        $("#detalles a").click(function(e){
            var page = $(this).attr("href");
            $.post(page,{},function(response){
                    $("#ContenidoDetalles").html(response);
                });
            $( "#dialog-form").dialog( "open" );
            $(".ui-dialog-titlebar-close").hide();
            e.preventDefault();            
            
        });

        $( "#dialog-form" ).dialog({
            autoOpen: false,
            // height: aut,
            width: 600,
            modal: true,
            buttons: {
            Ok: function() {
                $("#ContenidoDetalles").html('');
                $( this ).dialog( "close" );
            }
            },
            close: function() {
                allFields.val( "" ).removeClass( "ui-state-error");
            }
        });     
    }); 
  function abrirVentana(url) {
    window.open(url,"nuevo","directories=no,location=no,menubar=no,scrollbars=yes,statusbar=no,tittlebar=no,width=800,height=600")
  } 

</script>

<div id="dialog-form" title="Detalles de la compra">
        <fieldset id="ContenidoDetalles">
           
        </fieldset>
</div>