<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        overflow: hidden;
        text-align: center;
    }
    div#welcome #titulo{
      width: 800px;
    }

    div#more-information    {
        height: 100%;
    }
    #logoportada{
      width: 250px;
    }
    #textoportada{
      margin-top: -10px;
      background: url('/img/Letra-sistema-control.gif');
      height: 117px;
      width: 800px;
    }
</style>
<div id="welcome">
    <div id="textoportada"></div>
    <div>
        <p><img id='logoportada' src="/img/logo-oficial-punto4.gif"></p>
    </div>
    <div id="more-information">
        <p>
          <img src="/img/p4.gif">
        </p>
    </div>
</div>
<!-- 
<h2>Sistema de Administración de Ventas (SIAVE)</h2>


<a href="#" onClick="abrirVentana('http://punto4.local/async/')">Linea de Código</a><br />
<a href="#" onClick="abrirVentana('http://www.w3api.com')">W3Api</a><br />
<a href="#" onClick="abrirVentana('http://www.google.com')">Google</a>

<script type="text/javascript">
  function abrirVentana(url) {
    window.open(url,"nuevo","directories=no,location=no,menubar=no,scrollbars=yes,statusbar=no,tittlebar=no,width=400,height=400")
  }
</script>


<div id="myModal" class="modal hide fade" style="display: none; width:800px;">
            <div class="modal-header">
              <a class="close" data-dismiss="modal">×</a>
              <h3>Modal Heading</h3>
            </div>
            <div class="modal-body">
              <h4>Text in a modal</h4>
              <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem.</p>

              <h4>Popover in a modal</h4>
              <p>This <a href="#" class="btn popover-test" data-content="And here's some amazing content. It's very engaging. right?" data-original-title="A Title">button</a> should trigger a popover on hover.</p>

              <h4>Tooltips in a modal</h4>
              <p><a href="#" class="tooltip-test" data-original-title="Tooltip">This link</a> and <a href="#" class="tooltip-test" data-original-title="Tooltip">that link</a> should have tooltips on hover.</p>
            </div>
            <div class="modal-footer">
              <a href="#" class="btn btn-primary">Save changes</a>
              <a href="#" class="btn" data-dismiss="modal">Close</a>
            </div>
          </div>

<a data-toggle="modal" href="#myModal" class="btn btn-primary btn-large">Launch demo modal</a>          

<a href="#" class="btn btn-danger" rel="popover" data-content="No te gusta?" data-original-title="A Title">hover for popover</a> -->