
<h2 style="text-align:center;">Formulario</h2>	
<div id="form_agregar" class="well">
	    <div class="alert alert-block alert-info fade in">
            <a href="#" data-dismiss="alert" class="close">×</a>
            <h4 class="alert-heading">Importante:</h4>
            Solo tiene una catidad límite de 5 Privilegios para agregar.
            Los Privilegios te ayudan a controlar los usuarios de este sistema. ejm: Administrador, Cajero, Vendedor, etc. 
		</div>	
	    <a class="btn btn-success" href="/privilegio/list"><i class="icon-arrow-left icon-white"></i> Listar</a>
		<?php echo $this->form;?>
</div>