<article>
    <h2>Sección de Privilegio</h2>
    <div class="well">
        <label style="float:right;">
            <a class="btn" href="/privilegio/list"><i class="icon-refresh"></i> Actualizar</a>&nbsp;
            <a class="btn btn-info" href="/privilegio/add" id="create-new" title="Agregar Nuevo"><i class="icon-plus icon-white"></i> Nuevo </a>            
        </label>
    </div>
</article>
<article id="tblistar">
    <table class="table table-striped table-bordered table-condensed">
            <thead>
               <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                </tr>
            </thead>        
            <?php if( count( $this->paginator )) :?>
            <?php $contador = 0; ?>
            <tbody>
                <?php foreach ($this->paginator as $value) : ?>
                <?php $contador++; ?>           
                <tr>
                    <td><?php echo $value->idprivilegio;?></td>
                    <td><?php echo $value->pri_nombre;?></td>
                    <td><?php echo $value->pri_estado;?></td>
                    <td width="88">                      
                        <div class="btn-group">
                          <a class="btn btn-mini btn-primary" href="#">Acción</a>
                          <a class="btn btn-mini btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                          <ul class="dropdown-menu" style="text-align:left;">
                            <li><a href="/privilegio/update/id/<?php echo $value->idprivilegio; ?>"><i class="icon-pencil"></i> Editar</a></li>
                            <?php if ($value->pri_estado == 'Suspendido'):?>
                                <li><a href="/privilegio/active/id/<?php echo $value->idprivilegio; ?>"><i class="icon-trash"></i> Activar</a></li>   
                            <?php else: ?>
                                <li><a href="/privilegio/suspend/id/<?php echo $value->idprivilegio; ?>"><i class="icon-trash"></i> Suspender</a></li>   
                            <?php endif ?>
                            <li><a href="/privilegio/delete/id/<?php echo $value->idprivilegio; ?>"><i class="icon-trash"></i> Eliminar</a></li>
                          </ul>
                        </div>                      
                    </td>
                </tr>          
            <?php endforeach;?>
            </tbody>        
            <?php else : ?>
            <tbody>
                <tr>
                    <td colspan="4">No hay datos</td>
                </tr>
            </tbody>
            <?php endif;?> 
            <tfoot >
                <tr >
                    <td colspan="4">
                        <?php if( count( $this->paginator )):?>
                            <?php echo $this->paginator;?>
                        <?php endif;?>  
                    </td>
                </tr>      
            </tfoot>
    </table>
</article>