
<h2 style="text-align:center;">Formulario</h2>	
<div id="form_agregar" class="well">
	    <div class="alert alert-block alert-info fade in">
            <a href="#" data-dismiss="alert" class="close">×</a>
            <h4 class="alert-heading">Información:</h4>
            Los sucursales son las tiendas que se encuentran a parte de la tienda principal.
		</div>	
	    <a class="btn btn-success" href="/sucursal/list"><i class="icon-arrow-left icon-white"></i> Listar</a>
		<?php echo $this->form;?>
</div>