<article>
    <h2 >Sección de sucursales</h2>
    <div class="well">
        <label style="float:right;">
            <a class="btn" href="/sucursal/list"><i class="icon-refresh"></i> Actualizar</a>&nbsp;            
            <a class="btn btn-info" href="/sucursal/add" id="create-new" title="Agregar Nuevo"><i class="icon-plus icon-white"></i> Nuevo </a>            
        </label>
    </div>
</article>
<article id="tblistar">
    <table class="table table-striped table-bordered table-condensed">
            <thead>
               <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Dirección del sucursal</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                </tr>
            </thead>        
            <?php if( count( $this->paginator )) :?>
            <?php $contador = 0; ?>
            <tbody>
                <?php foreach ($this->paginator as $value) : ?>
                <?php $contador++; ?>           
                <tr>
                    <td><?php echo $value->idsucursal;?></td>
                    <td><?php echo $value->su_nombre;?></td>
                    <td><?php echo $value->su_direc;?></td>
                    <td><?php echo $value->su_estado;?></td>
                    <td width="88">                      
                        <div class="btn-group">
                          <a class="btn btn-mini btn-primary" href="#">Acción</a>
                          <a class="btn btn-mini btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                          <ul class="dropdown-menu" style="text-align:left;">
                            <li><a href="/sucursal/update/id/<?php echo $value->idsucursal; ?>"><i class="icon-pencil"></i> Editar</a></li>
                            <?php if ($value->su_estado == 'Suspendido'):?>
                                <li><a href="/sucursal/active/id/<?php echo $value->idsucursal; ?>"><i class="icon-trash"></i> Activar</a></li>   
                            <?php else: ?>
                                <li><a href="/sucursal/suspend/id/<?php echo $value->idsucursal; ?>"><i class="icon-trash"></i> Suspender</a></li>   
                            <?php endif ?>
                            <li><a href="/sucursal/delete/id/<?php echo $value->idsucursal; ?>"><i class="icon-trash"></i> Eliminar</a></li>
                          </ul>
                        </div>                      
                    </td>
                </tr>          
            <?php endforeach;?>
            </tbody>        
            <?php else : ?>
            <tbody>
                <tr>
                    <td colspan="5">No hay datos</td>
                </tr>
            </tbody>
            <?php endif;?> 
            <tfoot>
                <tr >
                    <td colspan="5">
                        <?php if( count( $this->paginator )):?>
                            <?php echo $this->paginator;?>
                        <?php endif;?>  
                    </td>
                </tr>      
            </tfoot>
    </table>
</article>
<!-- La parte en donde se busca para listar la lista en la parte de abajo -->
<script type="text/javascript">
    $(document).on("ready",iniciar);
    function iniciar(){
        //Para la actualización de los datos--INICIO
        var pagina='';
        $("#menu a").click(function(e){
            e.preventDefault();
            pagina=$(this).attr("href");
            $("#frmUpdate").load(pagina);        
            $( "#frmUpdate" ).dialog({
                autoOpen: false,
                height: 500,
                width: 500,
                modal: true,
                show: "drop",
                hide: "explode",
                buttons: {
                Cancelar: function() {
                    $( this ).dialog( "close" );
                }
                }
            });          
            $( "#frmUpdate").dialog( "open" );      
        });
        $('#frmUpdate').submit(function() {
                $.ajax(
                {
                    type: 'POST',
                    url: pagina,
                    data: $('#frmUpdate').serialize()
                });                  
                $("#frmUpdate").dialog( "close" );
        });
        //Para la actualización de los datos--FIN

        $("#frmbuscar").on("submit",buscar);
    }

    function inicioEnvio(){
       $("#tblistar").html('<img  src="/img/cargando.gif">');
    }
    function buscar(e){
        if($("#txtbuscar").val().length>0){
            e.preventDefault();            
            $("#tblistar").ajaxStart(inicioEnvio);
            $.post("/proveedor/search",{ txtbuscar:$("#txtbuscar").val() },mostrar);            
        }else{
            $("#frmbuscar span").addClass("label label-warning");
            $("#frmbuscar span").text("Ingrese el prámetro!!").show().fadeOut(5000);
            return false;
        }
    }
    function mostrar(data){  
        $("#tblistar").html(data);
    } 
</script>
