
<h2 style="text-align:center;">Formulario</h2>	
<div id="form_agregar" class="well">
	    <div class="alert alert-info fade in">
            <a href="#" data-dismiss="alert" class="close">×</a>
            <h4 class="alert-heading">Importante:</h4>
            Agrega tu link personalizado, puedes agregar los link dependiendo en que parte de la página quieres mostrarlo, para ello tienes que indicarle en la parte de abajo. 
		</div>	
	    <a class="btn btn-success" href="/link/list"><i class="icon-arrow-left icon-white"></i> Listar</a>
		<?php echo $this->form;?>
</div>