<article>
    <h2 style="text-align:center;">Asignación de Privilegios</h2>
    <div class="well">
        <div class="alert alert-info" id="resultado">
            En la parte de abajo se muestra todos los Links y los Privilegios para que tu puedas gestionar los permisos.
        </div>         
        <div style="float:right;">
            <a class="btn btn-success" href="/link/list"><i class="icon-list icon-white"></i> Listar</a> &nbsp;&nbsp; 
            <a class="btn" href="/link/privileges"><i class="icon-refresh"></i> Actualizar</a>&nbsp;&nbsp;            
            <a class="btn btn-info" href="/link/add" id="create-new" title="Agregar Nuevo"><i class="icon-plus icon-white"></i> Nuevo Link </a>&nbsp;&nbsp;
            <a class="btn btn-info" href="/privilegio/add" id="create-new" title="Agregar Nuevo"><i class="icon-plus icon-white"></i> Nuevo Privilegio</a>
        </div> 
        <br>                  
    </div>
</article>
<script type="text/javascript">
    $(document).on("ready",Iniciar);
    function Iniciar(){
        $("#optionsCheckbox input").click( function(){
            if(this.checked == false){
                var variable=$(this).val();
                // alert(variable);
                $.post("/link/checkedfalse",{variable:variable},function(data){$("#resultado").html(data)});
                $("#resultado").removeClass();
                $("#resultado").addClass("alert alert-success");
            }else{
                var variable=$(this).val();
                $.post("/link/checkedtrue",{variable:variable},function(data){$("#resultado").html(data)});
                $("#resultado").removeClass();
                $("#resultado").addClass("alert alert-success");
            }
        });
    }
    
</script>
<!-- <div id="resultado"></div> -->

<article id="tblistar">
    <table class="table table-striped table-bordered table-condensed">

    <!-- Recogiendo variables para la cantidad de los rows para poder controlarlo -->
    <?php $ContPrivilegio = count( $this->DataPrivilegio ); ?>
    <?php $ContLink = count( $this->DataLink ); ?>   

    <?php if($ContLink && $ContPrivilegio): ?>        
            <thead>
               <tr>
                    <th>Acciones</th>
                    <?php foreach ($this->DataPrivilegio as $value) : ?>
                        <th><?php echo $value->pri_nombre;?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>  
            <tbody id="optionsCheckbox">
                <?php foreach ($this->DataLink as $val) : ?>        
                <tr>
                    <td><?php echo $val->li_nombre;?></td>
                    <?php $i=0; ?>
                    <?php foreach ($this->DataPrivilegio as $val_pri) : ?>
                    <?php $i++; ?>
                        <td>
                            <?php if($val["li_pri$i"]==0): ?>
                                <label >
                                    <input type="checkbox" name="formPriv[]" value="<?php echo $val->idlink."-".$val_pri->idprivilegio."-"."li_pri".$i; ?>" id="optionsCheckbox">
                                </label>
                            <?php else: ?>
                                <label class="checkbox">
                                    <input type="checkbox" name="formPriv[]" value="<?php echo $val->idlink."-".$val_pri->idprivilegio."-"."li_pri".$i; ?>" id="optionsCheckbox" checked="checked">
                                </label>
                            <?php endif; ?>                          
                        </td>
                    <?php endforeach; ?>
                </tr>          
                <?php endforeach;?>
            </tbody>        
            <tfoot >
                <tr >
                    <td colspan="<?php echo $ContPrivilegio+1; ?>">>
                    </td>
                </tr>      
            </tfoot>
    <?php endif ?>


<!-- Cuando no hayga resultados de link y hayga Resultados de Privilegio -->
    <?php if(!$ContLink && $ContPrivilegio): ?>        
            <thead>
               <tr>
                    <th>Acciones</th>
                    <?php foreach ($this->DataPrivilegio as $value) : ?>
                        <th><?php echo $value->pri_nombre;?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>        
            <tbody>
                <tr>
                    <td colspan="<?php echo $ContPrivilegio+1; ?>">
                        <div class="alert alert-error">
                            <strong>Ups!</strong>
                            Lo sentimos, no se encontrarón ningún Link.
                        </div>
                    </td>
                </tr>
            </tbody>        
            <tfoot >
                <tr >
                    <td colspan="<?php echo $ContPrivilegio+1; ?>"></td>
                </tr>      
            </tfoot>
    <?php endif ?>


    <?php if($ContLink && !$ContPrivilegio): ?>        
            <thead>
               <tr>
                    <th>Acciones</th>
                        <th colspan="5">
                            <div class="alert alert-error">
                                    <strong>Ups!</strong>
                                    Lo sentimos, no se encontrarón ningún privilegio.
                            </div>
                        </th>
                </tr>
            </thead>        
            <tbody>
                <?php foreach ($this->DataLink as $val) : ?>        
                <tr>
                    <td><?php echo $val->li_nombre;?></td>
                </tr>          
                <?php endforeach;?>
            </tbody>        
            <tfoot >
                <tr >
                    <td colspan="6"></td>
                </tr>      
            </tfoot>
    <?php endif ?>


    <?php if(!$ContLink && !$ContPrivilegio): ?>        
            <thead>
               <tr>
                    <th>Acciones</th>
                        <th colspan="5">
                            <div class="alert alert-error">
                                    <strong>Ups!</strong>
                                    Lo sentimos, no se encontrarón ningún privilegio.
                            </div>
                        </th>
                </tr>
            </thead>        
            <tbody>
                <tr>
                    <td colspan="<?php echo $ContPrivilegio+1; ?>">
                        <div class="alert alert-error">
                            <strong>Ups!</strong>
                            Lo sentimos, no se encontrarón ningún Link.
                        </div>
                    </td>
                </tr>
            </tbody>        
            <tfoot >
                <tr >
                    <td colspan="6"></td>
                </tr>      
            </tfoot>
    <?php endif ?>

    </table>
</article>