<article>
    <h2>Sección de Clientes</h2>
    <form id="frmbuscar" class="well form-search">
      <input id="txtbuscar" type="text" class="input-large search-query" placeholder="Quieres Buscar?..">
      <button id="btnbuscar" type="submit" class="btn btn-inverse"><i class="icon-search icon-white"></i> Buscar</button>&nbsp;&nbsp;
        <span></span>
    <label style="float:right;">
        <a class="btn" href="/cliente/list"><i class="icon-refresh"></i> Actualizar</a>&nbsp;
        <a class="btn btn-info" href="/cliente/add" id="create-new" title="Agregar Nuevo"><i class="icon-plus icon-white"></i> Nuevo </a>
    </label>
    </form>
</article>
<article id="tblistar">
    <table class="table table-striped table-bordered table-condensed">
            <thead>
               <tr>
                    <th>Id</th>
                    <th>Documento</th>
                    <th>Nombre y Apellidos</th>
                    <th>Dirección</th>
                    <th>Fecha Ingreso</th>
                    <th>Teléfono</th>
                    <th>Email</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                </tr>
            </thead>        
            <?php if( count( $this->paginator )) :?>
            <tbody>
                <?php foreach ($this->paginator as $value) : ?>      
                <tr>
                    <td><?php echo $value->idcliente;?></td>
                    <td><?php echo $value->cl_docu;?></td>
                    <td><?php echo $value->cl_nombre;?></td>
                    <td><?php echo $value->cl_direc;?></td>
                    <td><?php echo $value->cl_fechingre;?></td>
                    <td><?php echo $value->cl_telf;?></td>
                    <td><?php echo $value->cl_email;?></td>
                    <td><?php echo $value->cl_estado;?></td>
                    <td width="77">                      
                        <div class="btn-group">
                          <a class="btn btn-mini btn-primary" href="#">Acción</a>
                          <a class="btn btn-mini btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                          <ul class="dropdown-menu" style="text-align:left;">
                            <li><a href="/cliente/update/id/<?php echo $value->idcliente; ?>" onclick= "AlertUpdate(<?php echo $value->idcliente; ?>)"><i class="icon-pencil"></i> Editar</a></li>
                            <?php if ($value->cl_estado == 'Suspendido'):?>
                                <li><a href="/cliente/active/id/<?php echo $value->idcliente; ?>" ><i class="icon-trash"></i> Activar</a></li>   
                            <?php else: ?>
                                <li><a href="/cliente/suspend/id/<?php echo $value->idcliente; ?>"><i class="icon-trash"></i> Suspender</a></li>   
                            <?php endif ?>
                            <li><a href="/cliente/delete/id/<?php echo $value->idcliente; ?>" onclick= "AlertUpdate(<?php echo $value->idcliente; ?>)"><i class="icon-trash"></i> Eliminar</a></li>
                          </ul>
                        </div>                      
                    </td>
                </tr>          
            <?php endforeach;?>
            </tbody>        
            <?php else : ?>
            <tbody>
                <tr>
                    <td colspan="9">No hay datos</td>
                </tr>
            </tbody>
            <?php endif;?> 
            <tfoot>
                <tr >
                    <td colspan="9">
                        <?php if( count( $this->paginator )):?>
                            <?php echo $this->paginator;?>
                        <?php endif;?>  
                    </td>
                </tr>      
            </tfoot>
    </table>
</article>
<script type="text/javascript">
    $(function(){
        // Script para buscar las compras
        $("#frmbuscar").submit(function(){
            $.post("/factura/search",{txtbuscar : $("#txtbuscar").val()},function(response){
                    var notice = response;
                     $("#tblistar").html(notice);
                });
            return false;
        });
    });


    function AlertDelete (argument) {
        if(confirm("Desea eliminar el registro?")){
            window.location.replace('/factura/delete/id/'+argument);
        }else{
            return false;
        }
    }
    function AlertUpdate (argument) {
        if(confirm("Realmente quiere modificar el registro?")){
            window.location.replace('/factura/update/id/'+argument);
        }else{
            return false;
        }
    }    
</script>
