<div>
    <h2>Sección de Recursos</h2>
    <form id="frmbuscar" class="well form-search">
        <input id="txtbuscar" type="text" class="input-large search-query" placeholder="Quieres Buscar?..">
        <button id="btnbuscar" type="submit" class="btn btn-inverse"><i class="icon-search icon-white"></i> Buscar</button>&nbsp;&nbsp;
        <span></span>
        <label style="float:right;">
            <a class="btn" href="/recurso/list"><i class="icon-refresh"></i> Actualizar</a>&nbsp;
            <a class="btn btn-info" href="/recurso/add" id="create-new" title="Agregar Nuevo"><i class="icon-plus icon-white"></i> Nuevo </a>
        </label>
    </form>
</div>
<div id="tblistar">
    <table class="table table-striped table-bordered table-condensed" style="font-size:11px;">
        <thead>
           <tr>
                <th>Id</th>
                <th>SKU</th>
                <th>Nombre del recurso</th>
                <th>Marca</th>
                <th>Stock</th>
                <th>Presentación</th>
                <th>UMedida</th>
                <th>P.Com</th>
                <th>P.Ven</th>
                <th>StockMin</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>        
        <?php if( count( $this->paginator )) :?>
        <tbody >
            <?php foreach ($this->paginator as $value) : ?>            
            <tr>
                <td><?php echo $value->idrecurso;?></td>
                <td><?php echo $value->re_sku;?></td>
                <td><?php echo $value->re_nombre;?></td>
                <td><?php echo $value->re_marca;?></td>
                <td><?php echo $value->re_stock;?></td>
                <td><?php echo $value->re_presenta;?></td>
                <td><?php echo $value->re_umedida;?></td>
                <td><?php echo $value->re_pcompra;?></td>
                <td><?php echo $value->re_pventa;?></td>
                <td><?php echo $value->re_stockmin;?></td>
                <td><?php echo $value->re_estado;?></td>                
                <td width="77">
                    <div class="btn-group">
                          <!-- <a class="btn btn-mini btn-primary" href="#">Acción</a> -->
                          <button class="btn btn-mini btn-primary">Acción</button>
                          <button class="btn btn-mini btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></button>
                          <ul class="dropdown-menu" style="text-align:left;">
                            <li><a href="/recurso/update/id/<?php echo $value->idrecurso; ?>"><i class="icon-pencil"></i> Editar</a></li>
                            <?php if ($value->re_estado == 'Suspendido'):?>
                                <li><a href="/recurso/active/id/<?php echo $value->idrecurso; ?>"><i class="icon-trash"></i> Activar</a></li>   
                            <?php else: ?>
                                <li><a href="/recurso/suspend/id/<?php echo $value->idrecurso; ?>"><i class="icon-trash"></i> Suspender</a></li>   
                            <?php endif ?>
                            <li id="acciones"><a href="/recurso/delete/id/<?php echo $value->idrecurso; ?>"><i class="icon-trash"></i> Eliminar</a></li>
                          </ul>
                    </div> 
                </td>
            </tr>          
        <?php endforeach;?>
        </tbody>        
        <?php else : ?>
        <tbody>
            <tr>
                <td colspan="12">No hay datos</td>
            </tr>
        </tbody>
        <?php endif;?> 
        <tfoot>
            <tr >
                <td colspan="12">
                    <?php if( count( $this->paginator )):?>
                        <?php echo $this->paginator;?>
                    <?php endif;?>  
                </td>
            </tr>      
        </tfoot>
    </table>
</div>
<!-- La parte en donde se busca para listar la lista en la parte de abajo -->
<script type="text/javascript">
    $(function(){
        $("#frmbuscar").submit(function(){
            $.post("/recurso/search",{txtbuscar : $("#txtbuscar").val()},function(response){
                    var notice = response;
                    $("#tblistar").html(notice);
                });
            return false;
        });

        // Evento para poder pedir confirmación al moneto de eliminar un registro
        $("#acciones a").click(function(e){            
            if (confirm('Realmente quiere eliminarlo el registro??')){
                return true;
            }
            else{
                e.preventDefault();
            }
        });      
    }); 
</script>
