
<h2 style="text-align:center;">Formulario</h2>	
<div id="form_agregar" class="well">
	    <a class="btn btn-success" href="/personal/list"><i class="icon-list icon-white"></i> Listar</a>
	    <a class="btn" href="/personal/add"><i class="icon-refresh"></i> Actualizar</a>
	    <br>
	    <br>
		<div class="alert alert-info" id="notices">
		            Llene el formulario teniendo en cuenta los requeridos que están con (*).
		</div>  	    
		<?php echo $this->form;?>
</div>

<script type="text/javascript">
	$(function(){
		$("#per_docu").focusout(function(){

			if($("#per_docu").val().length>0){
				$.post("/async/validperdocu",{per_docu :$("#per_docu").val() },function(response){
						// alert(response);
						if (response==3) {
							$('input[type="submit"]').attr('disabled','disabled');	
							$("#notices").removeClass();
							$("#notices").addClass("alert alert-error");	
							$("#notices").html("<h4 class='alert-heading'>Error</h4>El docuemtno de identidad Nro. '"+$("#per_docu").val()+"' No puede ser texto.");
						}
						if (response==1) {
							$('input[type="submit"]').attr('disabled','disabled');	
							$("#notices").removeClass();
							$("#notices").addClass("alert alert-error");	
							$("#notices").html("<h4 class='alert-heading'>Error</h4>El docuemtno de identidad Nro. "+$("#per_docu").val()+" que ingrsó ya se encuentra registrado.");
						}
						if(response == 0){	
							$('input[type="submit"]').removeAttr('disabled');
							$("#notices").removeClass();
							$("#notices").addClass("alert alert-success");						
							$("#notices").html("<h4 class='alert-heading'>Bién</h4>El documento de identidad Nro. "+$("#per_docu").val()+" está disponible. ;-)");
						}
					});
			}else{
				$('input[type="submit"]').attr('disabled','disabled');	
				$("#notices").removeClass();
				$("#notices").addClass("alert alert-error");	
				$("#notices").html("<h4 class='alert-heading'>Error</h4>El campo de DOCUMENTO DE IDENTIDAD o RUC no pueden estár vacío.");
			}
			return false;
		});
	});

</script>