<article>
    <h2>Sección de Boletas</h2>
    <form id="frmbuscar" class="well form-search">
      <input id="txtbuscar" type="text" class="input-large search-query" placeholder="Quieres Buscar?..">
      <button id="btnbuscar" type="submit" class="btn btn-inverse"><i class="icon-search icon-white"></i> Buscar</button>&nbsp;&nbsp;<span class="label label-warning">Buscar únicamente por Nro. de factura o emisor</span>
    </form>
</article>
<article id="tblistar">
    <table class="table table-striped table-bordered table-condensed">
            <thead>
               <tr>
                    <th>Id</th>
                    <th>NroBoleta</th>
                    <th>Fecha</th>
                    <th>Importe</th>
                    <th>Emisor</th>
                    <th>Acciones</th>
                </tr>
            </thead>        
            <?php if( count( $this->paginator )) :?>
            <tbody>
                <?php foreach ($this->paginator as $value) : ?>          
                <tr>
                    <td><?php echo $value->idboleta;?></td>
                    <td><?php echo $value->bo_nro;?></td>
                    <td><?php echo $value->bo_fech;?></td>
                    <td><?php echo $value->bo_importe;?></td>
                    <td><?php echo $value->bo_emisor;?></td>
                    <td width="88">                      
                        <div class="btn-group">
                          <a class="btn btn-mini btn-primary" href="#">Acción</a>
                          <a class="btn btn-mini btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                          <ul class="dropdown-menu" style="text-align:left;">
                            <li><a href="/boleta/update/id/<?php echo $value->idboleta; ?>" onclick= "AlertUpdate(<?php echo $value->idboleta; ?>)" rel="popover" data-content="Si modifica este registro todos los registros vendidos con esta boleta se modificaran automáticamente." data-original-title="Atención"><i class="icon-pencil"></i> Editar</a></li>
                            <li>
                                <a href="/boleta/delete/id/<?php echo $value->idboleta; ?>" onclick= "AlertDelete(<?php echo $value->idboleta; ?>)" rel="popover" data-content="Si elimina, se perderán totalmente todos los registros relacionados con esta boleta" data-original-title="Atención">
                                    <i class="icon-trash"></i> Eliminar
                                </a>
                            </li>
                          </ul>
                        </div>                      
                    </td>
                </tr>          
            <?php endforeach;?>
            </tbody>        
            <?php else : ?>
            <tbody>
                <tr>
                    <td colspan="6">No hay datos</td>
                </tr>
            </tbody>
            <?php endif;?> 
            <tfoot>
                <tr >
                    <td colspan="6">
                        <?php if( count( $this->paginator )):?>
                            <?php echo $this->paginator;?>
                        <?php endif;?>  
                    </td>
                </tr>      
            </tfoot>
    </table>
</article>
<script type="text/javascript">
    $(function(){
        // Script para buscar las compras
        $("#frmbuscar").submit(function(){
            $.post("/boleta/search",{txtbuscar : $("#txtbuscar").val()},function(response){
                    var notice = response;
                     $("#tblistar").html(notice);
                });
            return false;
        });
    });


    function AlertDelete (argument) {
        if(confirm("Desea eliminar el registro?")){
            window.location.replace('/boleta/delete/id/'+argument);
        }else{
            return false;
        }
    }
    function AlertUpdate (argument) {
        if(confirm("Realmente quiere modificar el registro?")){
            window.location.replace('/boleta/update/id/'+argument);
        }else{
            return false;
        }
    }    
</script>
